version: '2'
services:
    shivam-app:
        image: shivam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=shivam-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    shivam-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: shivam-cassandra
    shivam-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=shivam-cassandra
    shivam-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: shivam-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
